apiVersion: v1
kind: Service
metadata:
  name: hemp-service
spec:
  type: LoadBalancer
  selector:
    app: hemp
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 1200
    - name: db
      protocol: TCP
      port: 6006
      targetPort: 6006
