apiVersion: v1
kind: Service
metadata:
  name: hemp-service
spec:
  type: LoadBalancer
  selector:
    app: hemp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1200
    - protocol: TCP
        port: 6006
        targetPort: 6006