name: Build and Push Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login
      run: docker login -u ddatsko -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: cd server && docker build -t ddatsko/hemp:latest .
    - name: Push    
      run: cd server && docker push ddatsko/hemp:latest
